export const GET_FORM_DATA_EMPLEO_BUSCADOR = "GET_FORM_DATA_EMPLEO_BUSCADOR";
export const SET_FORM_DATA_EMPLEO_BUSCADOR = "SET_FORM_DATA_EMPLEO_BUSCADOR";
export const GET_EMPLEOS_DISPONIBLES = "GET_EMPLEOS_DISPONIBLES";
export const GET_USER_DATA = "GET_USER_DATA";
